#!/usr/bin/env bash
set -e

echo "Activating feature 'bitbucket-mcp'"

# Must stay in sync with the image tag in devcontainer-feature.json under
# customizations.vscode.mcp.servers. The consistency check in
# .github/workflows/validate.yml fails the build if the two ever diverge.
MCP_IMAGE="ghcr.io/fabianschurig/bitbucket-mcp:0.20.2"

MCP_SERVER_NAME="bitbucket-mcp-server"
ENV_FILE_REL=".config/bitbucket-mcp.env"
CONFIGURE_CURSOR="${CONFIGURECURSOR:-true}"

SHARE_DIR="/usr/local/share/bitbucket-mcp"
CONFIG_FILE="${SHARE_DIR}/config.env"
POST_CREATE="${SHARE_DIR}/post-create.sh"

TARGET_USER="${_REMOTE_USER:-root}"
TARGET_HOME="${_REMOTE_USER_HOME:-/root}"

echo "Image:            ${MCP_IMAGE}"
echo "Configure Cursor: ${CONFIGURE_CURSOR}"
echo "Target user:      ${TARGET_USER} (${TARGET_HOME})"

# The Cursor config is merged with jq so an existing ~/.cursor/mcp.json is never
# clobbered. Installing jq is best-effort: without it the post-create step
# degrades to printing the snippet rather than failing.
install_jq() {
    if command -v jq >/dev/null 2>&1; then
        return 0
    fi
    echo "jq not found, attempting to install it"
    if command -v apt-get >/dev/null 2>&1; then
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y && apt-get install -y --no-install-recommends jq
    elif command -v apk >/dev/null 2>&1; then
        apk add --no-cache jq
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y jq
    elif command -v microdnf >/dev/null 2>&1; then
        microdnf install -y jq
    elif command -v yum >/dev/null 2>&1; then
        yum install -y jq
    else
        echo "No supported package manager found, skipping jq installation"
    fi
}

install_jq || echo "WARNING: could not install jq, Cursor registration may be skipped at postCreate"

mkdir -p "$SHARE_DIR"

# Everything resolved at build time lives here, so post-create.sh stays pure
# logic and the tests can read the same values without re-deriving them.
cat > "$CONFIG_FILE" <<EOF
MCP_IMAGE="${MCP_IMAGE}"
MCP_SERVER_NAME="${MCP_SERVER_NAME}"
CONFIGURE_CURSOR="${CONFIGURE_CURSOR}"
TARGET_USER="${TARGET_USER}"
TARGET_HOME="${TARGET_HOME}"
ENV_FILE="${TARGET_HOME}/${ENV_FILE_REL}"
CURSOR_FILE="${TARGET_HOME}/.cursor/mcp.json"
EOF
chmod 644 "$CONFIG_FILE"

cat > "$POST_CREATE" <<'EOF'
#!/usr/bin/env bash
# Generated by the 'bitbucket-mcp' dev container feature. Do not edit.
set -u

# shellcheck source=/dev/null
. /usr/local/share/bitbucket-mcp/config.env

log() { echo "[bitbucket-mcp] $*"; }

# Keep ownership correct even if the hook is invoked as root.
fix_owner() {
    if [ "$(id -u)" = "0" ] && [ "$TARGET_USER" != "root" ]; then
        chown "$TARGET_USER" "$1" 2>/dev/null || true
    fi
}

# docker --env-file treats newlines as record separators, so a value that
# contains one would inject extra variables or truncate the token.
has_line_break() {
    case "$1" in
        *$'\n'*|*$'\r'*) return 0 ;;
        *) return 1 ;;
    esac
}

# A credentials file bind-mounted from the host is already in place before
# postCreate runs, so an existing file is always left exactly as it is.
seed_env_file() {
    if [ -e "$ENV_FILE" ]; then
        log "credentials file already present at ${ENV_FILE}, leaving it untouched"
        return 0
    fi

    mkdir -p "$(dirname "$ENV_FILE")" || return 1
    : > "$ENV_FILE" || return 1
    chmod 600 "$ENV_FILE"

    if [ -n "${BITBUCKET_USERNAME:-}" ] && [ -n "${BITBUCKET_TOKEN:-}" ] && \
        ! has_line_break "$BITBUCKET_USERNAME" && ! has_line_break "$BITBUCKET_TOKEN"; then
        # Unquoted on purpose: docker --env-file takes values verbatim, so
        # quotes would become part of the token and cause 401 Unauthorized.
        {
            printf 'BITBUCKET_USERNAME=%s\n' "$BITBUCKET_USERNAME"
            printf 'BITBUCKET_TOKEN=%s\n' "$BITBUCKET_TOKEN"
        } >> "$ENV_FILE"
        log "wrote credentials from the environment to ${ENV_FILE}"
    else
        if has_line_break "${BITBUCKET_USERNAME:-}" || has_line_break "${BITBUCKET_TOKEN:-}"; then
            log "WARNING: BITBUCKET_USERNAME/TOKEN contain a newline; writing the template instead"
        fi
        cat >> "$ENV_FILE" <<'TEMPLATE'
# Credentials for the Bitbucket MCP server, read by `docker run --env-file`.
# Do not quote the values: docker passes them through verbatim and the quotes
# would become part of the value, which causes 401 Unauthorized.
# See https://github.com/FabianSchurig/bitbucket-cli/blob/main/docs/mcp.md
#BITBUCKET_USERNAME=you@example.com
#BITBUCKET_TOKEN=your-api-token
TEMPLATE
        log "created an empty credentials template at ${ENV_FILE}"
        log "fill it in, or forward BITBUCKET_USERNAME and BITBUCKET_TOKEN via remoteEnv"
    fi

    fix_owner "$ENV_FILE"
}

manual_instructions() {
    log "add this to ${CURSOR_FILE} by hand, under \"mcpServers\":"
    log "  \"${MCP_SERVER_NAME}\": { \"type\": \"stdio\", \"command\": \"docker\", \"args\": [\"run\", \"--rm\", \"-i\", \"--env-file\", \"\${userHome}/.config/bitbucket-mcp.env\", \"${MCP_IMAGE}\"] }"
}

# Cursor does not read customizations.vscode.mcp, so it gets the same server
# definition written into its own global config instead.
configure_cursor() {
    if [ "$CONFIGURE_CURSOR" != "true" ]; then
        return 0
    fi

    if ! command -v jq >/dev/null 2>&1; then
        log "WARNING: jq is not available, skipping Cursor registration"
        manual_instructions
        return 0
    fi

    # ${userHome} stays literal here; Cursor resolves it when it reads the file.
    local server_json
    server_json=$(jq -n \
        --arg image "$MCP_IMAGE" \
        --arg envfile '${userHome}/.config/bitbucket-mcp.env' \
        '{type: "stdio", command: "docker", args: ["run", "--rm", "-i", "--env-file", $envfile, $image]}') || return 1

    mkdir -p "$(dirname "$CURSOR_FILE")" || return 1
    fix_owner "$(dirname "$CURSOR_FILE")"

    if [ ! -e "$CURSOR_FILE" ]; then
        jq -n --arg name "$MCP_SERVER_NAME" --argjson server "$server_json" \
            '{mcpServers: {($name): $server}}' > "$CURSOR_FILE" || return 1
        fix_owner "$CURSOR_FILE"
        log "registered ${MCP_SERVER_NAME} in ${CURSOR_FILE}"
        return 0
    fi

    if ! jq -e . "$CURSOR_FILE" >/dev/null 2>&1; then
        log "WARNING: ${CURSOR_FILE} is not valid JSON, leaving it untouched"
        manual_instructions
        return 0
    fi

    local current desired
    current=$(jq -cS --arg name "$MCP_SERVER_NAME" '.mcpServers[$name] // null' "$CURSOR_FILE") || return 1
    desired=$(printf '%s' "$server_json" | jq -cS .) || return 1
    if [ "$current" = "$desired" ]; then
        return 0
    fi

    cp -p "$CURSOR_FILE" "${CURSOR_FILE}.bak" 2>/dev/null || true

    local tmp
    tmp=$(mktemp "${CURSOR_FILE}.XXXXXX") || return 1
    if jq --arg name "$MCP_SERVER_NAME" --argjson server "$server_json" \
        '.mcpServers = ((.mcpServers // {}) + {($name): $server})' "$CURSOR_FILE" > "$tmp"; then
        mv "$tmp" "$CURSOR_FILE"
        fix_owner "$CURSOR_FILE"
        if [ "$current" = "null" ]; then
            log "registered ${MCP_SERVER_NAME} in ${CURSOR_FILE}"
        else
            log "updated ${MCP_SERVER_NAME} in ${CURSOR_FILE}, previous file backed up to ${CURSOR_FILE}.bak"
        fi
    else
        rm -f "$tmp"
        log "WARNING: could not update ${CURSOR_FILE}, leaving it untouched"
        manual_instructions
    fi
}

# The MCP server is launched as `docker run` from inside this container, so a
# missing Docker CLI breaks the server. It must not break the container.
check_docker() {
    if command -v docker >/dev/null 2>&1; then
        return 0
    fi
    log "WARNING: 'docker' was not found on PATH, so the MCP server cannot start."
    log "Add one of these to the features in your devcontainer.json:"
    log "  ghcr.io/devcontainers/features/docker-outside-of-docker:1"
    log "  ghcr.io/devcontainers/features/docker-in-docker:1"
}

seed_env_file || log "WARNING: could not create ${ENV_FILE}"
configure_cursor || log "WARNING: could not register the server with Cursor"
check_docker || true

# Never fail container creation because of MCP setup.
exit 0
EOF

chmod 755 "$POST_CREATE"

echo "Wrote ${CONFIG_FILE} and ${POST_CREATE}"
echo "Feature 'bitbucket-mcp' installed"
